### ISSUE TITLE
Set the time on the single board computer.

### ISSUE THREAD

**Issue by shaunluttin** [bigfont/2014-102MS-Monitoring#15]

**Comment by shaunluttin** [comment]
Time is a nuisance!

**Comment by matteric** [comment]
Failing this morning with this message:The fetch failed. Here is the error message: Network request failed

Matthew Salo902-940-3431 (mobile)250-728-3848 (day)

Date: Thu, 31 Mar 2016 20:15:47 -0700

**Comment by shaunluttin** [comment]
Thanks for letting me know. I have been making significant changes to add a
second sbc.

Shaun
