### ISSUE TITLE
Board 1 (port 12000) isn't showing history since 10:24pm.

### ISSUE THREAD

**Issue by shaunluttin** [bigfont/2014-102MS-Monitoring#18]

**Comment by shaunluttin** [comment]
This resulted from a improperly configured SBC port.

**Comment by shaunluttin** [comment]
Actually, the last comment was wrong. This failed because during refactoring, we had deleted the `Connection: close` HTTP header from the POST. Unit tests. I need to make some unit tests.

**Comment by matteric** [comment]
Ordered two 1/2" actuator valves for US$128 w/ shipping. Should arrive in about 1 week.

Matthew Salo902-940-3431 (mobile)250-728-3848 (day)

Date: Wed, 6 Apr 2016 16:27:18 -0700

**Comment by shaunluttin** [comment]
Cool. Not sure whether you meant that comment to appear here or not. :)
