### ISSUE TITLE
When I power off my Surface4, the power of the Surface Hub is insufficient. 

### ISSUE THREAD

**Issue by shaunluttin** [bigfont/2014-102MS-Monitoring#7]

**Comment by shaunluttin** [comment]
This is easily resolved by using a different power source than the Surface Hub.

**Comment by matteric** [comment]
yes,  something that delivers 12v would be nice, but 5v is adequate.  the cobra doc states the milliamps per machine

Matthew Salo902-940-3431 (mobile)250-728-3848 (day)

Date: Fri, 8 Apr 2016 07:15:23 -0700

**Comment by matteric** [comment]
did,t see the amps required in the specs for cobra iii--let alone cobra ii.  also suggests min voltage is 7vdc .  i think usb delivers 5v but to a different path.  there are onboard voltage regulators to drop the in voltsge to 5 and 3.3.

Matthew Salo902-940-3431 (mobile)250-728-3848 (day)

From: matthewsalo@hotmail.com
To: reply@reply.github.com
Subject: RE: [bigfont/2014-102MS-Monitoring] When I power off my Surface4, the power of the Surface Hub is insufficient.  (#7)
Date: Fri, 8 Apr 2016 07:18:38 -0700




yes,  something that delivers 12v would be nice, but 5v is adequate.  the cobra doc states the milliamps per machine

Matthew Salo902-940-3431 (mobile)250-728-3848 (day)

Date: Fri, 8 Apr 2016 07:15:23 -0700
